# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\DJANGO-NIKITA\NekrodBrick\interface\window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 540)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SettingsWidjet = QtWidgets.QWidget(self.centralwidget)
        self.SettingsWidjet.setObjectName("SettingsWidjet")
        self.formLayout = QtWidgets.QFormLayout(self.SettingsWidjet)
        self.formLayout.setObjectName("formLayout")
        self.BlackWhiteModeButton = QtWidgets.QRadioButton(self.SettingsWidjet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BlackWhiteModeButton.sizePolicy().hasHeightForWidth())
        self.BlackWhiteModeButton.setSizePolicy(sizePolicy)
        self.BlackWhiteModeButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.BlackWhiteModeButton.setObjectName("BlackWhiteModeButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.BlackWhiteModeButton)
        self.gridLayout_2.addWidget(self.SettingsWidjet, 0, 0, 1, 1)
        self.ImageView = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImageView.sizePolicy().hasHeightForWidth())
        self.ImageView.setSizePolicy(sizePolicy)
        self.ImageView.setMinimumSize(QtCore.QSize(520, 520))
        self.ImageView.setAutoFillBackground(False)
        self.ImageView.setObjectName("ImageView")
        self.gridLayout_2.addWidget(self.ImageView, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BlackWhiteModeButton.setText(_translate("MainWindow", "Чёрно-белый режим"))
